"""make candidate name nullable and add original_filename

Revision ID: 274b2b375ac4
Revises: 20260607_0001
Create Date: 2026-06-08 05:22:40.154023

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '274b2b375ac4'
down_revision: str | None = '20260607_0001'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('original_filename', sa.Text(), nullable=False))
    op.alter_column('candidates', 'name',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('candidates', 'name',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('candidates', 'original_filename')
    # ### end Alembic commands ###
