"""Add constraint fields to Candidate

Revision ID: a8b8503e21af
Revises: 274b2b375ac4
Create Date: 2026-06-08 07:11:06.755432

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'a8b8503e21af'
down_revision: str | None = '274b2b375ac4'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('desired_salary', sa.Integer(), nullable=True))
    op.add_column('candidates', sa.Column('visa_required', sa.Boolean(), nullable=True))
    op.add_column('candidates', sa.Column('preferred_location', sa.Text(), nullable=True))
    op.add_column('candidates', sa.Column('preferred_remote', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidates', 'preferred_remote')
    op.drop_column('candidates', 'preferred_location')
    op.drop_column('candidates', 'visa_required')
    op.drop_column('candidates', 'desired_salary')
    # ### end Alembic commands ###
