"""Make confidence and reasoning nullable

Revision ID: f17e2e028fa8
Revises: a8b8503e21af
Create Date: 2026-06-08 07:53:37.636640

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'f17e2e028fa8'
down_revision: str | None = 'a8b8503e21af'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('match_results', 'confidence',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('match_results', 'reasoning',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('match_results', 'reasoning',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('match_results', 'confidence',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    # ### end Alembic commands ###
